apiVersion: v1
kind: Service
metadata:
  name: backend_api_v_1_3_service
spec:
  type: NodePort
  selector:
    app: backend-api-v1-3
  ports:
    - name: http
      port: 80
      targetPort: 80
      type: LoadBalancer
