apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend-api
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
